### ISSUE TITLE
Slow data reading

### ISSUE THREAD

**Issue by evgenii-egorov** [franrruiz/shopper-src#5]
Hello!
Thank you for interesting paper and implementation.I would like to test it on my dataset, total 516218 lines. However, it more than 2 hours on "Reading data...+Stage 1/2..".  Seems also that it use only one thread to read the data. May be I am doing something wrong?

**Comment by franrruiz** [comment]
Hi - That might be indicative of a formatting error in the input files; I suggest carefully checking that.

Multithreading isn't applied to data reading, so it's normal that it uses one thread.

**Comment by evgenii-egorov** [comment]
Thank you for the fast response! It is really was the problem: I made '1.0' quantity instead of int.
